all: escritorfilho escritorpai leitor leitorpai leitor-2 leitor-3

escritorfilho:
	gcc -ansi -Wall -pedantic -o escritorfilho escritorfilho.c

escritorpai:
	gcc -ansi -Wall -pedantic -o escritorpai escritorpai.c
	
leitor:
	gcc -ansi -Wall -pedantic -o leitor leitor.c
	
leitor-pai:
	gcc -ansi -Wall -pedantic -o leitorpai leitorpai.c

leitor-2:
	gcc -ansi -Wall -pedantic -w -o leitor-2 leitor-2.c -lpthread 
	
leitor-3:
	gcc -ansi -Wall -pedantic -w -o leitor-3 leitor-3.c -lpthread 
