all: escritorfilho escritorpai leitor

escritorfilho:
	gcc -ansi -Wall -pedantic -o escritorfilho escritorfilho.c

escritorpai:
	gcc -ansi -Wall -pedantic -o escritorpai escritorpai.c
	
leitor:
	gcc -ansi -Wall -pedantic -o leitor leitor.c
	

